name: habit_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.3
  google_fonts: ^2.1.0 # to use google fonts
  shared_preferences: ^2.0.7 # to save data to device we use this to load onboard for first time only

flutter_native_splash:
  background_image: "assets/images/splash_image.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Klasik
      fonts:
        - asset: assets/fonts/Klasik Regular.otf
